#!/bin/bash
export JAVA_HOME="$OPENSHIFT_DATA_DIR/jdk"
export M2_HOME="$OPENSHIFT_DATA_DIR/maven"
export PATH=$JAVA_HOME/bin:$M2_HOME/bin:$PATH
cd $OPENSHIFT_REPO_DIR
mvn package -s .openshift/settings.xml -DskipTests=true
